<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
      <PackageReference Include="Telegram.Bot" Version="22.10.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Graber.Application\Graber.Application.csproj" />
      <ProjectReference Include="..\Graber.Infrastructure\Graber.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.production.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
